process.loadEnvFile()

export const {
  APP_PORT,
  DB_HOST,
  MYSQL_DIALECT,
  MYSQL_DATABASE,
  MYSQL_PORT,
  MYSQL_USER,
  MYSQL_PASSWORD,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_FOLDER_IMAGES,
  CLOUDINARY_FOLDER_FILES
} = process.env
